### ISSUE TITLE
nestjs 10 support

### ISSUE THREAD

**Issue by dalepo** [ntegral/nestjs-sentry#113]

**Comment by appinteractive** [comment]
hey @dalepo any luck? It was working initially and now suddenly stopped working with v10. 

@ntegral do you have some time looking into that?



I do get a bunch of GraphQLError`s with this module now, it complains about all schema entries:

```
GraphQLError: Input Object type UpdateUserInput must define one or more fields.
      at SchemaValidationContext.reportError (/Users/*/projects/nofapi/api/node_modules/graphql/type/validate.js:73:7)
      at validateInputFields (/Users/*/projects/nofapi/api/node_modules/graphql/type/validate.js:532:13)
      at validateTypes (/Users/*/projects/nofapi/api/node_modules/graphql/type/validate.js:260:7)
      at validateSchema (/Users/*/projects/nofapi/api/node_modules/graphql/type/validate.js:43:3)
      at graphqlImpl (/Users/*/projects/nofapi/api/node_modules/graphql/graphql.js:60:63)
      at /Users/*/projects/nofapi/api/node_modules/graphql/graphql.js:23:43
      at new Promise (<anonymous>)
      at graphql (/Users/*/projects/nofapi/api/node_modules/graphql/graphql.js:23:10)
      at GraphQLSchemaFactory.create (/Users/*/projects/nofapi/api/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:50:65)
      at GraphQLSchemaBuilder.generateSchema (/Users/*/projects/nofapi/api/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:35:52)
      at GraphQLSchemaBuilder.build (/Users/*/projects/nofapi/api/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:22:31)
      at GraphQLFactory.generateSchema (/Users/*/projects/nofapi/api/node_modules/@nestjs/graphql/dist/graphql.factory.js:27:69)
      at ApolloDriver.generateSchema (/Users/*/projects/nofapi/api/node_modules/@nestjs/graphql/dist/drivers/abstract-graphql.driver.js:23:36)
      at GraphQLModule.onModuleInit (/Users/*/projects/nofapi/api/node_modules/@nestjs/graphql/dist/graphql.module.js:109:54)
      at callModuleInitHook (/Users/*/projects/nofapi/api/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
      at NestApplication.callInitHook (/Users/*/projects/nofapi/api/node_modules/@nestjs/core/nest-application-context.js:223:13) {
    path: undefined,
    locations: undefined,
    extensions: [Object: null prototype] {}
  ```

**Comment by liranasia** [comment]
also waiting for support, had to bump versions and now not working with nestjs/common version 10

**Comment by appinteractive** [comment]
hey @liranasia for me it was the missing cli plugin support when using swc with nest 10. I needed to add @Field to every entity, arg, input properties and now it works.

**Comment by Kolahzary** [comment]
Currently `@ntegral/nestjs-sentry` is our only dependency which doesn't support nest 10:

![image](https://github.com/ntegral/nestjs-sentry/assets/6261271/24b71520-11e8-45d6-9023-7529b29fe7d1)

**Comment by alumni** [comment]
This should be fixed now.

However, I strongly recommend switching to [@travelerdev/nestjs-sentry](https://www.npmjs.com/package/@travelerdev/nestjs-sentry) since it has a better architecture (graphql separation) and other other fixes.
