### ISSUE TITLE
don`t work without graphql

### ISSUE THREAD

**Issue by eduscrakozabrus** [ntegral/nestjs-sentry#32]
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'graphql'
Require stack:
- /dist/node_modules/@nestjs/graphql/dist/decorators/directive.decorator.js
- /dist/node_modules/@nestjs/graphql/dist/decorators/index.js
- /dist/node_modules/@nestjs/graphql/dist/index.js
- /dist/node_modules/@nestjs/graphql/index.js
- /dist/node_modules/@ntegral/nestjs-sentry/dist/sentry.interceptor.js
- /dist/node_modules/@ntegral/nestjs-sentry/dist/index.js
- /dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/dist/node_modules/@nestjs/graphql/dist/decorators/directive.decorator.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/dist/node_modules/@nestjs/graphql/dist/decorators/index.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/dist/node_modules/@nestjs/graphql/dist/decorators/directive.decorator.js',
    '/dist/node_modules/@nestjs/graphql/dist/decorators/index.js',
    '/dist/node_modules/@nestjs/graphql/dist/index.js',
    '/dist/node_modules/@nestjs/graphql/index.js',
    '/dist/node_modules/@ntegral/nestjs-sentry/dist/sentry.interceptor.js',
    '/dist/node_modules/@ntegral/nestjs-sentry/dist/index.js',
    '/dist/main.js'
  ]

**Comment by wodka** [comment]
this is not related to this library - you have not yet setup graphql: https://docs.nestjs.com/graphql/quick-start#installation

**Comment by ntegral** [comment]
GraphQL is only required if you want to use the GraphQlInterceptor.  Please use the latest released version

**Comment by jannomeister** [comment]
I'm also experiencing it. I'm using the latest version

**Comment by jtag05** [comment]
@ntegral this is an issue, so please reopen. Every one of my services started complaining about needing graphql after upgrading to 2.0.6. Looking at the `/dist/index.js` you are exporting the `GraphQlInterceptor` directly from there which I would imagine is causing the entire package to rely on graphql existing.

**Comment by Gbuomprisco** [comment]
Agree with @jtag05 - that's likely to be the issue

**Comment by jtag05** [comment]
@Gbuomprisco oddly enough, a strict requirement on 2.0.5 will complain about the graphql requirements during build time, but at runtime it still functions. 2.0.6 is completely borked though.

**Comment by polyakova** [comment]
I have the same issue. Do you have a solution for it?

**Comment by xRiot** [comment]
Same issue here even though we don't use Graphql anywhere in our codebase

**Comment by wdospinal** [comment]
Do we have updates on this? same problem with version _"@ntegral/nestjs-sentry": "^2.0.6"_

**Comment by martinsotirov** [comment]
Same problem but weirdly enough on `2.0.5`. I haven't tried `2.0.6`.
