### ISSUE TITLE
Error: Cannot find module 'graphql'

### ISSUE THREAD

**Issue by adrianwix** [ntegral/nestjs-sentry#40]
Package ask for graphql to be installed even if it's an optionalDependency
"@ntegral/nestjs-sentry": "^2.0.6"
```
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'graphql'
Require stack:
- /home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/dist/decorators/directive.decorator.js
- /home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/dist/decorators/index.js
- /home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/dist/index.js
- /home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/index.js
- /home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ntegral/nestjs-sentry/dist/graphql.interceptor.js
- /home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ntegral/nestjs-sentry/dist/index.js
- /home/adrian/code/posterlab-mvp/nest-backend/dist/src/app.module.js
- /home/adrian/code/posterlab-mvp/nest-backend/dist/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._resolveFilename (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/dist/decorators/directive.decorator.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/dist/decorators/directive.decorator.js',
    '/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/dist/decorators/index.js',
    '/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/dist/index.js',
    '/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@nestjs/graphql/index.js',
    '/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ntegral/nestjs-sentry/dist/graphql.interceptor.js',
    '/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ntegral/nestjs-sentry/dist/index.js',
    '/home/adrian/code/posterlab-mvp/nest-backend/dist/src/app.module.js',
    '/home/adrian/code/posterlab-mvp/nest-backend/dist/src/main.js'
  ]
}
```

**Comment by ntegral** [comment]
Please update the the latest version of the @ntegral/nestjs-sentry module.  This should be fixed now. @adrianwix 

@adamtester, @jeremyhalin, @eduscrakozabrus , @jTanG0506, @wodka, @jannomeister, @jtag05, @Gbuomprisco ,@wdospinal , @martinsotirov 

Sorry about that.... This issue should be fixed in the latest version of the code!!! I'm going to blame it on COVID.   Thanks for your patience.

**Comment by adrianwix** [comment]
No problem, thanks for answering this fast

**Comment by wdospinal** [comment]
I'll check this, thanks for answering
