### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by nabeelsuspg** [ntegral/nestjs-sentry#49]
I have used the `SentryModule.forRoot` example as mentioned in the readme file. 

Error logs:
```
let SentryService = SentryService_1 = class SentryService extends common_1.ConsoleLogger {
TypeError: Class extends value undefined is not a constructor or null                                                                                                                            
at Object.<anonymous> (C:\project\server\node_modules\@ntegral\nestjs-sentry\dist\sentry.service.js:39:76)
at Module._compile (internal/modules/cjs/loader.js:1138:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
at Module.load (internal/modules/cjs/loader.js:986:32)
at Function.Module._load (internal/modules/cjs/loader.js:879:14)
at Module.require (internal/modules/cjs/loader.js:1026:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (C:\project\server\node_modules\@ntegral\nestjs-sentry\dist\sentry-core.module.js:21:26)
at Module._compile (internal/modules/cjs/loader.js:1138:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

Versions:
```
    "@nestjs/common": "6.5.3",
    "@nestjs/core": "6.5.3",
    "@nestjs/jwt": "6.1.1",
    "@nestjs/passport": "6.1.0",
    "@nestjs/platform-express": "6.5.3",
    "@nestjs/serve-static": "^2.1.3",
    "@nestjs/swagger": "3.1.0",
    "@nestjs/typeorm": "6.1.3",
    "@ntegral/nestjs-sentry": "^3.0.3",
    "@sentry/node": "^6.10.0",
    "@sentry/tracing": "^6.10.0",
    "node": "12.18.0"
```
Please suggest a workaround/way forward.

**Comment by nabeelsuspg** [comment]
@ntegral please suggest something about this bug.

**Comment by ntegral** [comment]
Can you please provide your package.json

**Comment by nabeelsuspg** [comment]
@ntegral  Following is my package.json file:
```
{
  "name": "energymanager",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "license": "MIT",
  "main": "dist/main.js",
  "scripts": {
    "clean": "rimraf dist",
    "build": "npm run clean && tsc -p tsconfig.build.json && npm run copy-resources",
    "webpack:prod": "npm run clean && webpack --config webpack.server.prod.config.js && npm run copy-resources",
    "copy-resources": "ts-node scripts/copy-resources.ts",
    "format": "prettier --write \"src/**/*.ts\"",
    "sonar:scanner": "sonar-scanner",
    "start:node": "npm run copy-resources && ts-node -r tsconfig-paths/register src/main.ts",
    "start:dev": "npm run copy-resources && tsc-watch -p tsconfig.build.json --onSuccess \"node dist/main.js\"",
    "start:debug": "npm run copy-resources && tsc-watch -p tsconfig.build.json --onSuccess \"node --inspect dist/main.js\"",
    "start:prod": "npm run copy-resources && node dist/main.js",
    "start": "npm run clean && npm run copy-resources && nodemon --watch src -e ts,tsx --exec ts-node src/main.ts",
    "lint": "eslint . --ignore-path .server.eslintignore --no-eslintrc --config .server.eslintrc.json --ext .js,.ts",
    "lint:fix": "npm run lint -- --fix",
    "test": "npm run lint && jest",
    "test:cov": "jest --coverage",
    "test:watch": "jest --watch",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --coverage --config ./e2e/jest.e2e.config.json",
    "standalone": "node --stack-trace-limit=1000 --stack-size=2048 --async-stack-traces ."
  },
  "dependencies": {
    "@nestjs/common": "6.5.3",
    "@nestjs/core": "6.5.3",
    "@nestjs/jwt": "6.1.1",
    "@nestjs/passport": "6.1.0",
    "@nestjs/platform-express": "6.5.3",
    "@nestjs/serve-static": "^2.1.3",
    "@nestjs/swagger": "3.1.0",
    "@nestjs/typeorm": "6.1.3",
    "@ntegral/nestjs-sentry": "^3.0.3",
    "@sentry/node": "^6.10.0",
    "@sentry/tracing": "^6.10.0",
    "async": "^3.2.0",
    "async-mutex": "^0.2.4",
    "aws-sdk": "^2.771.0",
    "axios": "^0.19.2",
    "bcrypt": "^5.0.0",
    "class-transformer": "0.2.3",
    "class-validator": "0.10.0",
    "cloud-config-client": "1.4.2",
    "date-fns": "^2.16.1",
    "dotenv": "^8.1.0",
    "ejs": "^3.1.3",
    "env-var": "^6.2.0",
    "eureka-js-client": "4.5.0",
    "geolib": "^3.3.1",
    "js-yaml": "3.13.1",
    "moment": "^2.29.1",
    "nodemailer": "^6.4.10",
    "passport": "0.4.0",
    "passport-jwt": "4.0.0",
    "pg": "^8.2.1",
    "randomstring": "^1.1.5",
    "reflect-metadata": "0.1.13",
    "rxjs": "6.5.2",
    "swagger-ui-express": "4.0.7",
    "ts-japi": "^1.2.7",
    "typeorm": "^0.2.31",
    "xlsx": "^0.16.9",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "@nestjs/testing": "6.5.3",
    "@types/async": "^3.2.3",
    "@types/aws-sdk": "^2.7.0",
    "@types/bcrypt": "^3.0.0",
    "@types/ejs": "^3.0.4",
    "@types/express": "4.17.1",
    "@types/express-serve-static-core": "4.17.3",
    "@types/jest": "24.0.18",
    "@types/lodash": "^4.14.165",
    "@types/node": "^11.13.4",
    "@types/nodemailer": "^6.4.0",
    "@types/passport-jwt": "3.0.1",
    "@types/randomstring": "^1.1.6",
    "@types/supertest": "2.0.8",
    "@types/uuid": "^8.0.0",
    "@typescript-eslint/eslint-plugin": "2.11.0",
    "@typescript-eslint/eslint-plugin-tslint": "2.11.0",
    "@typescript-eslint/parser": "2.11.0",
    "eslint": "6.7.2",
    "eslint-config-prettier": "6.7.0",
    "eslint-loader": "3.0.3",
    "jest": "24.7.1",
    "jest-diff": "^25.1.0",
    "nodemon": "1.19.1",
    "prettier": "1.17.0",
    "pretty-format": "^25.1.0",
    "rimraf": "3.0.0",
    "sonarqube-scanner": "2.5.0",
    "supertest": "4.0.2",
    "ts-jest": "24.0.2",
    "ts-node": "8.1.0",
    "tsc-watch": "2.2.1",
    "tsconfig-paths": "3.8.0",
    "tslint": "5.20.1",
    "typescript": "3.4.3",
    "uuid": "^8.2.0",
    "webpack": "4.41.5"
  },
  "engines": {
    "node": "12.18.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "testRegex": "(/test/.*|\\.(spec))\\.(ts|js)$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "coverage",
    "testEnvironment": "node",
    "setupFiles": [
      "dotenv/config"
    ]
  },
  "resolutions": {
    "jest-diff": "25.1.0",
    "pretty-format": "25.1.0"
  }
}

```

**Comment by ntegral** [comment]
https://github.com/ntegral/nestjs-sentry

You need to use the version @ntegral/nestjs-sentry@2.0.9

the version that you are trying to use only supports nestjs 8 or higher...

Version 3.x.x will support NestJS 8+. If you need support for NestJS 7 please continue to use Version 2.x.x. Thanks for you support!

**Comment by nabeelsuspg** [comment]
@ntegral sure. I will try the version you just shared. Please do not close the issue so that I can tell here if that works which will be helpful for others. Thank you.

**Comment by ntegral** [comment]
I'll sync the ReadME file in a version update

**Comment by nabeelsuspg** [comment]
Thank you.

**Comment by ntegral** [comment]
You're welcome. I'm closing this issue
